"""
polyglot/glue/generators/ffi_gen.py — Python<->C/C++ via cffi.

Generates Python-side cffi builder + C bridge stubs. All C functions
return 0 / NULL with a comment — the developer must implement them.
Scaffold only.
"""

import os
from polyglot.glue.glue_schema import (
    GlueSchema,
    GlueOutputPackage,
    now_iso,
    SCAFFOLD_DISCLAIMER,
)
from polyglot.glue.generators.plugin import PluginInterface, GeneratorMetadata, PluginRegistry

GENERATOR_HEADER = """// GENERATED BY glue-engineer v3 -- SCAFFOLD CODE
// SCHEMA: glue-schema-v1
// PAIR: {pair_id}
// STRATEGY: ffi_cffi (Python <-> C/C++)
// DISCLAIMER: FFI bridges require THOROUGH review of memory management,
// type casting, and buffer handling. Do not deploy without review.
// Generated: {timestamp}

"""


@PluginRegistry.register
class FFICffiGenerator(PluginInterface):
    """Generates cffi-based FFI bridge between Python and C/C++.

    Produces:
    - build_glue.py — cffi builder script
    - glue.py — Python-side FFI interface
    - glue_c_bridge.c — C bridge stubs
    """

    metadata = GeneratorMetadata(
        mode="ffi_cffi",
        description="Python<->C/C++ via cffi",
        source_languages=("python",),
        target_languages=("c_cpp",),
        confidence="low",
        version="1.0.0",
    )

    def generate(self, schema: GlueSchema, output_dir: str = ".glue/search") -> GlueOutputPackage:
        pair_id = schema.pair_id
        pair_dir = os.path.join(output_dir, pair_id)
        gen_dir = os.path.join(pair_dir, "generated")
        os.makedirs(gen_dir, exist_ok=True)

        src_name = schema.src.name if schema.src else "src"
        dst_name = schema.dst.name if schema.dst else "dst"

        generated_files = []

        # 1. C bridge stubs
        c_path = os.path.join(gen_dir, "glue_c_bridge.c")
        c_code = self._generate_c_bridge(schema, src_name, dst_name)
        with open(c_path, "w", encoding="utf-8") as f:
            f.write(c_code)
        generated_files.append(c_path)

        # 2. cffi builder
        builder_path = os.path.join(gen_dir, "build_glue.py")
        with open(builder_path, "w", encoding="utf-8") as f:
            f.write(self._generate_cffi_builder(schema))
        generated_files.append(builder_path)

        # 3. Python glue
        glue_path = os.path.join(gen_dir, "glue.py")
        with open(glue_path, "w", encoding="utf-8") as f:
            f.write(self._generate_python_glue(schema))
        generated_files.append(glue_path)

        # 4. __init__.py
        init_path = os.path.join(gen_dir, "__init__.py")
        with open(init_path, "w", encoding="utf-8") as f:
            f.write(f'"""FFI bridge: {pair_id}."""\nfrom .glue import *\n')
        generated_files.append(init_path)

        # 5. requirements.txt
        req_path = os.path.join(pair_dir, "requirements.txt")
        with open(req_path, "w", encoding="utf-8") as f:
            f.write(f"cffi>=1.16\n# TODO: add C library dependencies\n")
        generated_files.append(req_path)

        # 6. build.sh
        build_path = os.path.join(pair_dir, "build.sh")
        with open(build_path, "w", encoding="utf-8") as f:
            f.write(self._generate_build_sh(schema))
        generated_files.append(build_path)

        # 7. README
        readme_path = os.path.join(pair_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(self._generate_readme(schema))
        generated_files.append(readme_path)

        # 8. schema.json
        schema_path = os.path.join(pair_dir, "schema.json")
        with open(schema_path, "w", encoding="utf-8") as f:
            f.write(schema.to_json())
        generated_files.append(schema_path)

        package = GlueOutputPackage(
            glue_schema=schema,
            output_paths=generated_files,
            generated_at=now_iso(),
        )
        schema.output_dir = pair_dir
        schema.generated_files = generated_files
        return package

    def _generate_c_bridge(self, schema, src_name, dst_name) -> str:
        """Generate C bridge stubs."""
        header = GENERATOR_HEADER.format(pair_id=schema.pair_id, timestamp=now_iso())
        lines = [header]

        lines.extend([
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "#include <stdint.h>",
            "",
            "// TODO: include the actual C/C++ library headers",
            f"// #include <{dst_name}.h>",
            "",
            "// TODO: define error handling macros",
            "#define BRIDGE_OK 0",
            "#define BRIDGE_ERROR -1",
            "",
        ])

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.extend([
                f"/*",
                f" * Bridge: {m.src_function} -> {dst_name}.{m.dst_function}",
                f" * Confidence: {m.confidence} ({m.confidence_label})",
                f" *",
                f" * TODO: implement the actual call to {dst_name}_{m.dst_function}",
                f" * TODO: handle memory allocation and error propagation",
                f" */",
                f"int bridge_{m.src_function}(/* TODO: add params */) {{",
                f"    // TODO: call {dst_name}_{m.dst_function}(...)",
                f"    // TODO: handle return value and error cases",
                f'    fprintf(stderr, "bridge_{m.src_function}: not implemented\\n");',
                f"    return BRIDGE_ERROR;",
                f"}}",
                "",
            ])

        return "\n".join(lines)

    def _generate_cffi_builder(self, schema) -> str:
        """Generate cffi builder script."""
        lines = [
            f'"""cffi builder for {schema.pair_id} bridge."""',
            f"# GENERATED BY glue-engineer v3 -- SCAFFOLD CODE",
            f"",
            f"from cffi import FFI",
            f"",
            f"ffi = FFI()",
            f"",
            f'ffi.cdef("""',
            f"// TODO: declare C function signatures for the bridge",
            f"// int bridge_func_name(int param1, const char* param2);",
            f'""")',
            f"",
            f"if __name__ == '__main__':",
            f"    # TODO: set the source path to your compiled C library",
            f"    # ffi.set_source(",
            f"    #     '{schema.pair_id}_bridge',",
            f"    #     '#include \"glue_c_bridge.c\"',",
            f"    #     sources=['glue_c_bridge.c'],",
            f"    #     libraries=['your_c_library'],",
            f"    # )",
            f"    # ffi.compile()",
            f'    print("Edit this script to set the correct source path and re-run.")',
            f"    print(f\"Generated bridge for {schema.pair_id}\")",
        ]
        return "\n".join(lines)

    def _generate_python_glue(self, schema) -> str:
        """Generate Python-side FFI wrapper."""
        lines = [
            f'"""Python-side FFI glue for {schema.pair_id} bridge."""',
            f"# GENERATED BY glue-engineer v3 -- SCAFFOLD CODE",
            f"",
            f"# TODO: Import the compiled cffi module",
            f"# from _glue_c_bridge import ffi, lib",
            f"",
            f"# TODO: define wrapper classes and functions",
        ]

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.extend([
                "",
                f"# Mapping: {m.src_function} -> {m.dst_function}",
                f"# Confidence: {m.confidence} ({m.confidence_label})",
                f"# TODO: define Python wrapper for this bridge function",
                f"# def {m.src_function}_via_c(*args):",
                f"#     \"\"\"Call C bridge function.\"\"\"",
                f"#     # TODO: convert Python types to C types",
                f"#     # result = lib.bridge_{m.src_function}(...)",
                f"#     # TODO: convert C result back to Python",
                f"#     # return result",
                f"#     raise NotImplementedError(\"FFI bridge stub\")",
            ])

        return "\n".join(lines)

    def _generate_build_sh(self, schema) -> str:
        """Generate build script for C code."""
        bridge_name = schema.pair_id.replace("-", "_")
        return f"""#!/bin/bash
# Build {schema.pair_id} FFI bridge
set -e
cd "$(dirname "$0")"/generated

# Compile C bridge as shared library
echo "Compiling C bridge..."
gcc -c -fPIC glue_c_bridge.c -o glue_c_bridge.o
# TODO: link with the actual library
# gcc -shared -o lib{bridge_name}.so glue_c_bridge.o -lyour_library

# Build cffi module
python build_glue.py

echo "FFI bridge built. Import with: from generated.glue import *"
"""

    def _generate_readme(self, schema) -> str:
        dst_name = schema.dst.name if schema.dst else "?"
        return f"""# {schema.pair_id} — FFI/C Bridge

**Strategy:** ffi_cffi (Python <-> C/C++)
**Generated:** {now_iso()}

## Overview

Bridges **{schema.src.name if schema.src else '?'}** (Python) to **{dst_name}** (C/C++) via cffi.

## Files

- `generated/glue_c_bridge.c` — C bridge stubs (implement these!)
- `generated/build_glue.py` — cffi builder (configure this!)
- `generated/glue.py` — Python-side wrappers
- `build.sh` — Build script

## Usage

1. Implement the C functions in `glue_c_bridge.c`
2. Edit `build_glue.py` to set the correct include/library paths
3. Run `./build.sh`
4. `from generated.glue import your_function`

## Review Checklist

- [ ] Implement all C bridge function bodies
- [ ] Review memory allocation and deallocation
- [ ] Verify type casting between Python and C types
- [ ] Check buffer overflow protection
- [ ] Test with null/empty inputs
- [ ] Verify the shared library loads correctly

## Disclaimer

{SCAFFOLD_DISCLAIMER}"""

    def _ensure_mapping(self, m):
        if isinstance(m, dict):
            return type("Obj", (), {
                "src_function": m.get("src_function", ""),
                "dst_function": m.get("dst_function", ""),
                "confidence": m.get("confidence", 0.0),
                "confidence_label": m.get("confidence_label", ""),
            })()
        return m