"""
polyglot/glue/generators/import_gen.py — Same-language import glue generator.

Produces Python wrapper modules that bridge two libraries in the same language.
This is the highest-confidence strategy because there's no cross-language barrier.
"""

import os
from polyglot.glue.glue_schema import (
    GlueSchema,
    GlueOutputPackage,
    FunctionMapping,
    now_iso,
    SCAFFOLD_DISCLAIMER,
)
from polyglot.glue.generators.plugin import PluginInterface, GeneratorMetadata, PluginRegistry

GENERATOR_HEADER = """# GENERATED BY glue-engineer v3 -- SCAFFOLD CODE
# SCHEMA: glue-schema-v1
# PAIR: {pair_id}
# STRATEGY: import (same-language)
# DISCLAIMER: This is scaffold code. Manual review required before deployment.
# Generated: {timestamp}

"""


@PluginRegistry.register
class ImportGenerator(PluginInterface):
    """Generates same-language import bridge code.

    Wraps two Python libraries so that calls to library A are routed
    through to library B with parameter transformations.
    """

    metadata = GeneratorMetadata(
        mode="import",
        description="Same-language import wrapper (highest confidence)",
        source_languages=(
            "python", "javascript", "rust", "java", "kotlin", "c_cpp",
        ),
        target_languages=(
            "python", "javascript", "rust", "java", "kotlin", "c_cpp",
        ),
        confidence="high",
        version="1.0.0",
    )

    def generate(self, schema: GlueSchema, output_dir: str = ".glue/search") -> GlueOutputPackage:
        """Generate glue code for same-language import strategy."""
        pair_id = schema.pair_id
        pair_dir = os.path.join(output_dir, pair_id)
        gen_dir = os.path.join(pair_dir, "generated")
        os.makedirs(gen_dir, exist_ok=True)

        src_name = schema.src.name if schema.src else "src"
        dst_name = schema.dst.name if schema.dst else "dst"

        # Determine language-specific file extension
        ext = self._get_extension(schema)
        generated_files = []

        # Generate main glue file
        glue_path = os.path.join(gen_dir, f"glue{ext}")
        glue_code = self._generate_glue_module(schema, src_name, dst_name)
        with open(glue_path, "w", encoding="utf-8") as f:
            f.write(glue_code)
        generated_files.append(glue_path)

        # Generate __init__.py for the gen_dir
        init_path = os.path.join(gen_dir, "__init__.py")
        with open(init_path, "w", encoding="utf-8") as f:
            f.write(f'"""Glue bridge: {pair_id}."""\nfrom .glue import *\n')
        generated_files.append(init_path)

        # Generate requirements.txt
        req_path = os.path.join(pair_dir, "requirements.txt")
        with open(req_path, "w", encoding="utf-8") as f:
            f.write(self._generate_requirements(schema))
        generated_files.append(req_path)

        # Generate README
        readme_path = os.path.join(pair_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(self._generate_readme(schema))
        generated_files.append(readme_path)

        # Generate schema.json
        schema_path = os.path.join(pair_dir, "schema.json")
        with open(schema_path, "w", encoding="utf-8") as f:
            f.write(schema.to_json())
        generated_files.append(schema_path)

        package = GlueOutputPackage(
            glue_schema=schema,
            output_paths=generated_files,
            generated_at=now_iso(),
        )
        package.generated_files = generated_files
        schema.output_dir = pair_dir
        schema.generated_files = generated_files
        return package

    def _get_extension(self, schema: GlueSchema) -> str:
        """Get the appropriate file extension for the source language."""
        lang = schema.src.language if schema.src else "python"
        ext_map = {
            "python": ".py",
            "javascript": ".js",
            "rust": ".rs",
            "java": ".java",
            "kotlin": ".kt",
            "c_cpp": ".c",
        }
        return ext_map.get(lang, ".py")

    def _generate_glue_module(self, schema: GlueSchema, src_name: str, dst_name: str) -> str:
        """Generate the main glue module code."""
        lang = schema.src.language if schema.src else "python"

        header = GENERATOR_HEADER.format(pair_id=schema.pair_id, timestamp=now_iso())

        if lang == "javascript":
            return self._generate_js_glue(header, src_name, dst_name, schema)
        elif lang == "rust":
            return self._generate_rust_glue(header, src_name, dst_name, schema)
        elif lang == "java":
            return self._generate_java_glue(header, src_name, dst_name, schema)
        elif lang == "kotlin":
            return self._generate_kotlin_glue(header, src_name, dst_name, schema)
        else:
            # Default: Python
            return self._generate_python_glue(header, src_name, dst_name, schema)

    def _generate_python_glue(self, header: str, src_name: str, dst_name: str, schema: GlueSchema) -> str:
        """Generate Python glue module."""
        lines = [header]
        lines.append(f'"""Glue bridge: {schema.pair_id}. Routes {src_name} calls to {dst_name}."""\n')
        lines.append(f"import {src_name}")
        lines.append(f"import {dst_name}\n")

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            confidence = m.confidence
            label = m.confidence_label

            lines.append(f"# ------------------------------------------------------------------")
            lines.append(f"# Mapping: {m.src_function} -> {m.dst_function}")
            lines.append(f"# Confidence: {confidence} ({label})")
            lines.append(f"# Review status: {m.review_status}")
            lines.append(f"# ------------------------------------------------------------------")

            # Generate the bridge function
            if label in ("identical", "similar"):
                snippet = self._generate_python_identical(m, src_name, dst_name)
            else:
                snippet = self._generate_python_low_conf(m, src_name, dst_name)

            lines.append(snippet)
            lines.append("")

        # Add main guard with example usage
        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append('    print(f"Glue bridge: {src_name} <-> {dst_name}")')
        lines.append('    print("This module provides mapped function calls.")')
        lines.append("    # Example usage (uncomment to run):")
        if schema.mappings:
            m = self._ensure_mapping(schema.mappings[0])
            lines.append(f"    # result = {m.src_function}_via_{dst_name}(...)")
            lines.append(f"    # print(result)")

        return "\n".join(lines)

    def _generate_python_identical(self, mapping, src_name: str, dst_name: str) -> str:
        """Generate a high-confidence bridge function for Python."""
        src_func = mapping.src_function
        dst_func = mapping.dst_function

        # Collect parameters
        src_params = []
        param_body = []
        for pm in mapping.param_mappings:
            pm = self._ensure_param_mapping(pm)
            if pm.dst_name == "#MISSING":
                src_params.append(pm.src_name)
                param_body.append(f"    # TODO: src param '{pm.src_name}' has no dst match")
            elif pm.transform and pm.transform.kind == "identity":
                src_params.append(pm.src_name)
            else:
                src_params.append(pm.src_name)

        params_str = ", ".join(src_params) if src_params else "*args, **kwargs"
        params_fwd = ", ".join(
            pm.dst_name if pm.dst_name != "#MISSING" else f"# TODO: {pm.src_name}"
            for pm in mapping.param_mappings
        ) if mapping.param_mappings else "*args, **kwargs"

        lines = []
        lines.append(f"")
        lines.append(f"def {src_func}_via_{dst_name}({params_str}):")
        lines.append(f'    """Bridge: {src_name}.{src_func} -> {dst_name}.{dst_func}"""')

        # Add TODO markers for low-confidence params
        for pm in mapping.param_mappings:
            pm = self._ensure_param_mapping(pm)
            if pm.dst_name == "#MISSING":
                lines.append(f'    # TODO: param "{pm.src_name}" not mapped — may need manual handling')
            elif pm.transform and pm.transform.kind != "identity":
                lines.append(f'    # TODO: check param transform for "{pm.src_name}" -> "{pm.dst_name}"')

        if mapping.return_transform and mapping.return_transform.kind != "identity":
            lines.append(f"    # TODO: return type transform needed")

        lines.append(f"    try:")
        if mapping.param_mappings:
            lines.append(f"        result = {dst_name}.{dst_func}({params_fwd})")
        else:
            lines.append(f"        result = {dst_name}.{dst_func}()")
        lines.append(f"        return result")
        lines.append(f"    except Exception as e:")
        lines.append(f'        raise RuntimeError(f"Bridge error in {src_func} -> {dst_func}: {{e}}") from e')

        return "\n".join(lines)

    def _generate_python_low_conf(self, mapping, src_name: str, dst_name: str) -> str:
        """Generate a low-confidence bridge function with extra warnings."""
        src_func = mapping.src_function
        dst_func = mapping.dst_function

        lines = [
            "",
            f"# TODO: LOW CONFIDENCE MAPPING ({mapping.confidence}) — manual review required",
            f"def {src_func}_via_{dst_name}(*args, **kwargs):",
            f'    """Bridge: {src_name}.{src_func} -> {dst_name}.{dst_func}',
            "",
            f"    WARNING: This is a low-confidence mapping ({mapping.confidence_label}).",
            '    Verify the parameter semantics before use.',
            f'    """',
            f"    # TODO: verify these parameter mappings",
        ]

        for pm in mapping.param_mappings:
            pm = self._ensure_param_mapping(pm)
            lines.append(f"    # src.{pm.src_name} -> dst.{pm.dst_name}")

        lines.append(f"    try:")
        lines.append(f"        result = {dst_name}.{dst_func}(*args, **kwargs)")
        lines.append(f"        return result")
        lines.append(f"    except Exception as e:")
        lines.append(f'        raise RuntimeError(f"Bridge error in {src_func} -> {dst_func}: {{e}}") from e')

        return "\n".join(lines)

    def _generate_js_glue(self, header: str, src_name: str, dst_name: str, schema: GlueSchema) -> str:
        """Generate JavaScript glue module."""
        lines = [header]
        lines.append(f"// Glue bridge: {schema.pair_id}")
        lines.append(f"// Routes {src_name} calls to {dst_name}\n")
        lines.append(f"const {src_name} = require('{src_name}');")
        lines.append(f"const {dst_name} = require('{dst_name}');\n")

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f"// Mapping: {m.src_function} -> {m.dst_function} (confidence: {m.confidence})")

            def _get_pm_name(pm): return pm.src_name if hasattr(pm, 'src_name') else getattr(pm, 'get', lambda k, d='': d)('src_name', '')
            def _get_pm_dst(pm): return pm.dst_name if hasattr(pm, 'dst_name') else getattr(pm, 'get', lambda k, d='': d)('dst_name', '')
            js_params = [_get_pm_name(pm) for pm in (m.param_mappings or []) if _get_pm_dst(pm) != '#MISSING']
            js_params_str = ", ".join(js_params) if js_params else "*args"

            lines.append(f"function {m.src_function}_via_{dst_name}({js_params_str}) {{")
            lines.append(f"  // TODO: manual review required")
            lines.append(f"  try {{")
            lines.append(f"    const result = {dst_name}.{m.dst_function}({js_params_str});")
            lines.append(f"    return result;")
            lines.append(f"  }} catch (e) {{")
            lines.append(f'    throw new Error(`Bridge error in {m.src_function}: ${{e.message}}`);')
            lines.append(f"  }}")
            lines.append(f"}}\n")

        lines.append(f"module.exports = {{")
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f"  {m.src_function}_via_{dst_name},")
        lines.append(f"}};\n")
        return "\n".join(lines)

    def _generate_rust_glue(self, header, src_name, dst_name, schema):
        """Generate Rust glue module."""
        lines = [header]
        lines.append(f"// Glue bridge: {schema.pair_id}")
        lines.append(f"// Routes {src_name} calls to {dst_name}")
        lines.append(f"// NOTE: This is a scaffold for same-language Rust <-> Rust bridging.")
        lines.append(f"// In Rust, 'same-language' means both crates compile in the same binary.")
        lines.append(f"")
        lines.append(f"use {src_name};")
        lines.append(f"use {dst_name};")
        lines.append(f"")

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            params = [pm.src_name for pm in (m.param_mappings or []) if getattr(pm, 'dst_name', getattr(pm, 'dst_name', '')) != '#MISSING']
            param_str = ", ".join(f"{p}: impl Into<???>" for p in params) if params else ""

            lines.append(f"/// Mapping: {m.src_function} -> {m.dst_function}")
            lines.append(f"/// Confidence: {m.confidence} ({m.confidence_label})")
            lines.append(f"pub fn {m.src_function}_via_{dst_name}({param_str}) -> todo!() {{")
            lines.append(f"    // TODO: implement bridge body")
            lines.append(f"    // This is a scaffold function — the actual call to")
            lines.append(f"    // {dst_name}::{m.dst_function}() needs to be written.")
            lines.append(f"    todo!()")
            lines.append(f"}}")
            lines.append(f"")

        return "\n".join(lines)

    def _generate_java_glue(self, header, src_name, dst_name, schema):
        """Generate Java glue module."""
        src_class = src_name.title().replace("-", "").replace("_", "")
        dst_class = dst_name.title().replace("-", "").replace("_", "")
        lines = [header]
        lines.append(f"// Glue bridge: {schema.pair_id}")
        lines.append(f"// Routes {src_name} calls to {dst_name}")
        lines.append(f"")
        lines.append(f"public class {src_class}To{dst_class}Bridge {{")
        lines.append(f"")

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f"    /** Mapping: {m.src_function} -> {m.dst_function} (confidence: {m.confidence}) */")
            lines.append(f"    // TODO: define proper parameter types")
            lines.append(f"    public static Object {m.src_function}_via_{dst_class}(Object... args) {{")
            lines.append(f"        try {{")
            lines.append(f"            // TODO: call {dst_name}.{m.dst_function} with mapped params")
            lines.append(f"            // Object result = {dst_class}.{m.dst_function}(args);")
            lines.append(f"            // return result;")
            lines.append(f"            throw new UnsupportedOperationException(\"Scaffold — implement bridge\");")
            lines.append(f"        }} catch (Exception e) {{")
            lines.append(f'            throw new RuntimeException("Bridge error: " + e.getMessage(), e);')
            lines.append(f"        }}")
            lines.append(f"    }}")
            lines.append(f"")

        lines.append(f"}}")
        return "\n".join(lines)

    def _generate_kotlin_glue(self, header, src_name, dst_name, schema):
        """Generate Kotlin glue module."""
        lines = [header]
        lines.append(f"// Glue bridge: {schema.pair_id}")
        lines.append(f"// Routes {src_name} calls to {dst_name}")
        lines.append(f"")
        lines.append(f"object {src_name.title().replace('-','')}To{dst_name.title().replace('-','')}Bridge {{")
        lines.append(f"")

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f"    /** Mapping: {m.src_function} -> {m.dst_function} (confidence: {m.confidence}) */")
            lines.append(f"    // TODO: define proper parameter types and return type")
            lines.append(f"    fun {m.src_function}_via_{dst_name}(vararg args: Any?): Any? {{")
            lines.append(f"        return try {{")
            lines.append(f"            // TODO: call {dst_name}.{m.dst_function} with mapped parameters")
            lines.append(f'            throw NotImplementedError("Scaffold — implement bridge")')
            lines.append(f"        }} catch (e: Exception) {{")
            lines.append(f'            throw RuntimeException("Bridge error: ${e.message}", e)')
            lines.append(f"        }}")
            lines.append(f"    }}")
            lines.append(f"")

        lines.append(f"}}")
        return "\n".join(lines)

    def _generate_requirements(self, schema: GlueSchema) -> str:
        """Generate requirements.txt with known dependencies."""
        lines = [f"# Generated dependencies for {schema.pair_id}"]
        lines.append(f"# These are scaffold-level pins — verify before deploying.\n")
        if schema.src:
            lines.append(f"{schema.src.name}>={schema.src.version}" if schema.src.version else schema.src.name)
        if schema.dst:
            lines.append(f"{schema.dst.name}>={schema.dst.version}" if schema.dst.version else schema.dst.name)
        lines.append("")
        return "\n".join(lines)

    def _generate_readme(self, schema: GlueSchema) -> str:
        """Generate README with review checklist."""
        lines = [
            f"# {schema.pair_id} — Glue Bridge",
            f"",
            f"**Strategy:** import (same-language)",
            f"**Generated:** {now_iso()}",
            f"",
            f"## Overview",
            f"",
            f"Bridges **{schema.src.name if schema.src else '?'}** ({schema.src.language if schema.src else '?'}) "
            f"to **{schema.dst.name if schema.dst else '?'}** ({schema.dst.language if schema.dst else '?'})",
            f"",
            f"## Review Checklist",
            f"",
            f"- [ ] Verify all function parameter mappings are correct",
            f"- [ ] Check edge case handling (null, empty, overflow, timeout)",
            f"- [ ] Add logging around bridge calls",
            f"- [ ] Verify error propagation works as expected",
            f"- [ ] Run the generated tests",
            f"",
            f"## Disclaimer",
            f"",
            f"{SCAFFOLD_DISCLAIMER}",
        ]
        return "\n".join(lines)

    def _ensure_mapping(self, m):
        """Normalize mapping to FunctionMapping object."""
        if isinstance(m, dict):
            return FunctionMapping(**m)
        return m

    def _ensure_param_mapping(self, pm):
        """Normalize param mapping to ParamMapping object."""
        if isinstance(pm, dict):
            return type("Obj", (), {
                "src_name": pm.get("src_name", ""),
                "dst_name": pm.get("dst_name", ""),
                "transform": type("Obj", (), {"kind": "identity", "expr": ""})() if pm.get("transform") else None,
                "src_default": pm.get("src_default", ""),
                "dst_default": pm.get("dst_default", ""),
            })()
        return pm
