"""
polyglot/glue/generators/pyo3_gen.py — Python->Rust native extension via PyO3.

Generates Cargo.toml + lib.rs with PyO3 bindings. All function bodies
are `todo!()` — the developer must implement the actual calls to the
Rust library. Scaffold only.
"""

import os
from polyglot.glue.glue_schema import (
    GlueSchema,
    GlueOutputPackage,
    now_iso,
    SCAFFOLD_DISCLAIMER,
)
from polyglot.glue.generators.plugin import PluginInterface, GeneratorMetadata, PluginRegistry

GENERATOR_HEADER = """// GENERATED BY glue-engineer v3 -- SCAFFOLD CODE
// SCHEMA: glue-schema-v1
// PAIR: {pair_id}
// STRATEGY: pyo3 (Python -> Rust native extension)
// DISCLAIMER: All function bodies are `todo!()` — they require implementation.
// Native extension bridges require thorough review of all type conversions,
// memory management, and GIL behavior.
// Generated: {timestamp}

"""


@PluginRegistry.register
class PyO3Generator(PluginInterface):
    """Generates PyO3 native extension stubs.

    Produces:
    - Cargo.toml with pyo3 + dst_library dependencies
    - src/lib.rs with #[pyfunction] and #[pymodule] stubs
    - pyproject.toml for maturin build
    """

    metadata = GeneratorMetadata(
        mode="pyo3",
        description="Python->Rust native extension via PyO3",
        source_languages=("python",),
        target_languages=("rust",),
        confidence="low",
        version="1.0.0",
    )

    def generate(self, schema: GlueSchema, output_dir: str = ".glue/search") -> GlueOutputPackage:
        pair_id = schema.pair_id
        pair_dir = os.path.join(output_dir, pair_id)
        gen_dir = os.path.join(pair_dir, "generated", "src")
        os.makedirs(gen_dir, exist_ok=True)

        dst_name = schema.dst.name if schema.dst else "dst"

        generated_files = []

        # 1. Cargo.toml
        cargo_path = os.path.join(pair_dir, "generated", "Cargo.toml")
        cargo_code = self._generate_cargo_toml(schema, dst_name)
        with open(cargo_path, "w", encoding="utf-8") as f:
            f.write(cargo_code)
        generated_files.append(cargo_path)

        # 2. lib.rs
        lib_path = os.path.join(gen_dir, "lib.rs")
        lib_code = self._generate_lib_rs(schema, dst_name)
        with open(lib_path, "w", encoding="utf-8") as f:
            f.write(lib_code)
        generated_files.append(lib_path)

        # 3. pyproject.toml
        pyproject_path = os.path.join(pair_dir, "generated", "pyproject.toml")
        with open(pyproject_path, "w", encoding="utf-8") as f:
            f.write(self._generate_pyproject_toml(schema))
        generated_files.append(pyproject_path)

        # 4. build.sh
        build_path = os.path.join(pair_dir, "build.sh")
        with open(build_path, "w", encoding="utf-8") as f:
            f.write(self._generate_build_sh(schema))
        generated_files.append(build_path)

        # 5. README
        readme_path = os.path.join(pair_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(self._generate_readme(schema))
        generated_files.append(readme_path)

        # 6. schema.json
        schema_path = os.path.join(pair_dir, "schema.json")
        with open(schema_path, "w", encoding="utf-8") as f:
            f.write(schema.to_json())
        generated_files.append(schema_path)

        package = GlueOutputPackage(
            glue_schema=schema,
            output_paths=generated_files,
            generated_at=now_iso(),
        )
        schema.output_dir = pair_dir
        schema.generated_files = generated_files
        return package

    def _generate_cargo_toml(self, schema, dst_name) -> str:
        """Generate Cargo.toml with pyo3 dependency."""
        dst_name_safe = dst_name.lower().replace("-", "_").replace(" ", "_")
        lines = [
            f"[package]",
            f'name = "{schema.pair_id}"',
            f'version = "0.1.0"',
            f'edition = "2021"',
            f"",
            f"[lib]",
            f'name = "{schema.pair_id}"',
            f'crate-type = ["cdylib"]',
            f"",
            f"[dependencies]",
            f'pyo3 = {{ version = "0.21", features = ["extension-module"] }}',
            f'serde = {{ version = "1", features = ["derive"] }}',
            f'serde_json = "1"',
            f'# TODO: add the actual dependency for {dst_name}',
            f'# {dst_name_safe} = "{{version}}"',
            f"",
        ]
        return "\n".join(lines)

    def _generate_lib_rs(self, schema, dst_name) -> str:
        """Generate lib.rs with #[pyfunction] stubs."""
        header = GENERATOR_HEADER.format(pair_id=schema.pair_id, timestamp=now_iso())
        lines = [header]

        lines.extend([
            f"use pyo3::prelude::*;",
            f"use pyo3::exceptions::PyRuntimeError;",
            f"use serde_json;",
            f"",
            f"// TODO: add `use {dst_name.lower().replace('-', '_')};` after adding to Cargo.toml",
            f"",
        ])

        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            src_func = m.src_function
            dst_func = m.dst_function

            lines.extend([
                f"/// Bridge: {src_func} -> {dst_name}.{dst_func}",
                f"/// Confidence: {m.confidence} ({m.confidence_label})",
                f"///",
                f"/// TODO: implement actual call to {dst_name}::{dst_func}",
                f"/// TODO: handle type conversions and error mapping",
                f"#[pyfunction]",
                f'#[pyo3(text_signature = "(...)" )]',
                f"fn {src_func}_via_rust(",
                f"    py: Python<'_>,",
                f"    // TODO: add parameters matching {dst_name}.{dst_func}",
                f") -> PyResult<PyObject> {{",
                f"    // TODO: Deserialize Python input",
                f"    // TODO: Call {dst_name}::{dst_func}()",
                f"    // TODO: Serialize result back to Python object",
                f'    Err(PyRuntimeError::new_err("Not implemented: {src_func} bridge"))',
                f"}}",
                f"",
            ])

        # Generate the module
        mod_name = schema.pair_id.replace("-", "_")
        lines.extend([
            f"/// {schema.pair_id} — PyO3 native extension module",
            f"#[pymodule]",
            f"fn {mod_name}(m: &Bound<'_, PyModule>) -> PyResult<()> {{",
        ])
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f'    m.add_function(wrap_pyfunction!({m.src_function}_via_rust, m)?)?;')
        lines.append(f"    Ok(())")
        lines.append(f"}}")

        return "\n".join(lines)

    def _generate_pyproject_toml(self, schema) -> str:
        """Generate pyproject.toml for maturin build."""
        return f"""[build-system]
requires = ["maturin>=1.0", "setuptools", "wheel"]
build-backend = "maturin"

[project]
name = "{schema.pair_id}"
version = "0.1.0"
description = "PyO3 native extension bridge: {schema.pair_id}"
requires-python = ">=3.8"

[tool.maturin]
features = ["pyo3/extension-module"]
"""

    def _generate_build_sh(self, schema) -> str:
        """Generate build script."""
        return f"""#!/bin/bash
# Build {schema.pair_id} PyO3 extension
set -e
cd "$(dirname "$0")"/generated

# Install maturin if needed
# pip install maturin

# Build in debug mode
maturin develop

# For release build:
# maturin build --release
echo "PyO3 extension built. Import with: import {schema.pair_id.replace('-', '_')}"
"""

    def _generate_readme(self, schema) -> str:
        return f"""# {schema.pair_id} — PyO3 Native Bridge

**Strategy:** pyo3 (Python -> Rust native extension)
**Generated:** {now_iso()}

## Overview

Bridges **{schema.src.name if schema.src else '?'}** (Python) to **{schema.dst.name if schema.dst else '?'}** (Rust)
via a PyO3 native extension module.

## Files

- `generated/Cargo.toml` — Rust project config (add the real dependency!)
- `generated/src/lib.rs` — PyO3 bindings (implement the todo!() bodies!)
- `generated/pyproject.toml` — Maturin build config
- `build.sh` — Build and install the extension

## Usage

1. Edit `Cargo.toml` to add the actual `{schema.dst.name if schema.dst else '?'}` dependency
2. Implement the function bodies in `src/lib.rs`
3. Run `./build.sh`
4. `import {schema.pair_id.replace('-', '_')}` in Python

## Review Checklist

- [ ] Verify Rust type conversions are correct for all mapped functions
- [ ] Check GIL handling (pyo3 GIL guards, allow_threads where appropriate)
- [ ] Review error propagation: Rust panics -> Python exceptions
- [ ] Test with real data payloads
- [ ] Verify the build produces a platform-compatible wheel

## Disclaimer

{SCAFFOLD_DISCLAIMER}"""

    def _ensure_mapping(self, m):
        if isinstance(m, dict):
            return type("Obj", (), {
                "src_function": m.get("src_function", ""),
                "dst_function": m.get("dst_function", ""),
                "confidence": m.get("confidence", 0.0),
                "confidence_label": m.get("confidence_label", ""),
                "param_mappings": m.get("param_mappings", []),
            })()
        return m