"""
polyglot/glue/generators/subprocess_gen.py — Cross-language subprocess+JSON bridge.

Produces a Python host that launches a foreign-language child process and
communicates via JSON-over-stdin/stdout. Universal fallback strategy.
"""

import os
from polyglot.glue.glue_schema import (
    GlueSchema,
    GlueOutputPackage,
    FunctionMapping,
    now_iso,
    SCAFFOLD_DISCLAIMER,
)
from polyglot.glue.generators.plugin import PluginInterface, GeneratorMetadata, PluginRegistry

GENERATOR_HEADER = """# GENERATED BY glue-engineer v3 -- SCAFFOLD CODE
# SCHEMA: glue-schema-v1
# PAIR: {pair_id}
# STRATEGY: subprocess_json (cross-language bridge)
# DISCLAIMER: Cross-language bridges require THOROUGH review of all type
# conversions and error propagation. Do not deploy without review.
# Generated: {timestamp}

"""


@PluginRegistry.register
class SubprocessGenerator(PluginInterface):
    """Generates cross-language subprocess+JSON bridge code.

    SPI Protocol: JSON on stdin -> JSON on stdout with {ok: bool, result/error}.
    """

    metadata = GeneratorMetadata(
        mode="subprocess_json",
        description="Cross-language subprocess+JSON bridge (universal)",
        source_languages=("python",),
        target_languages=("javascript", "rust", "java", "kotlin", "c_cpp"),
        confidence="medium",
        version="1.0.0",
    )

    def generate(self, schema: GlueSchema, output_dir: str = "glue-outputs") -> GlueOutputPackage:
        pair_id = schema.pair_id
        pair_dir = os.path.join(output_dir, pair_id)
        gen_dir = os.path.join(pair_dir, "generated")
        os.makedirs(gen_dir, exist_ok=True)

        src_name = schema.src.name if schema.src else "src"
        dst_name = schema.dst.name if schema.dst else "dst"
        dst_lang = schema.dst.language if schema.dst else "foreign"

        generated_files = []

        # 1. Python host-side glue
        glue_path = os.path.join(gen_dir, "glue.py")
        glue_code = self._generate_python_host(schema, src_name, dst_name, dst_lang)
        with open(glue_path, "w", encoding="utf-8") as f:
            f.write(glue_code)
        generated_files.append(glue_path)

        # 2. Foreign-side bridge CLI
        bridge_ext = self._bridge_extension(dst_lang)
        bridge_path = os.path.join(gen_dir, f"bridge{bridge_ext}")
        bridge_code = self._generate_foreign_bridge(schema, src_name, dst_name, dst_lang)
        with open(bridge_path, "w", encoding="utf-8") as f:
            f.write(bridge_code)
        generated_files.append(bridge_path)

        # 3. __init__.py
        init_path = os.path.join(gen_dir, "__init__.py")
        with open(init_path, "w", encoding="utf-8") as f:
            f.write(f'"""Subprocess bridge: {pair_id}."""\nfrom .glue import *\n')
        generated_files.append(init_path)

        # 4. requirements.txt
        req_path = os.path.join(pair_dir, "requirements.txt")
        with open(req_path, "w", encoding="utf-8") as f:
            f.write(f"# Requirements for {pair_id} bridge host\n{schema.src.name or ''}\n")
        generated_files.append(req_path)

        # 5. Build script
        build_path = os.path.join(pair_dir, "build.sh")
        with open(build_path, "w", encoding="utf-8") as f:
            f.write(self._generate_build_script(schema, dst_lang))
        generated_files.append(build_path)

        # 6. README
        readme_path = os.path.join(pair_dir, "README.md")
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(self._generate_readme(schema, dst_lang))
        generated_files.append(readme_path)

        # 7. schema.json
        schema_path = os.path.join(pair_dir, "schema.json")
        with open(schema_path, "w", encoding="utf-8") as f:
            f.write(schema.to_json())
        generated_files.append(schema_path)

        package = GlueOutputPackage(
            glue_schema=schema,
            output_paths=generated_files,
            generated_at=now_iso(),
        )
        schema.output_dir = pair_dir
        schema.generated_files = generated_files
        return package

    def _generate_python_host(self, schema, src_name, dst_name, dst_lang) -> str:
        """Generate the Python host-side BridgeClient class."""
        header = GENERATOR_HEADER.format(pair_id=schema.pair_id, timestamp=now_iso())
        lines = [header]

        lines.append('"""')
        lines.append(f'Subprocess bridge host — {schema.pair_id}')
        lines.append(f'')
        lines.append(f'Spawns a {dst_lang} child process and communicates via JSON/stdio.')
        lines.append(f'Each call sends a JSON command to the bridge and parses the response.')
        lines.append(f'{"-" * 60}')
        lines.append(f'SPI Protocol:')
        lines.append(f'  Request:  {{"method": "func_name", "params": [...]}}')
        lines.append(f'  Response: {{"ok": true, "result": ...}}')
        lines.append(f'           {{"ok": false, "error": "message"}}')
        lines.append(f'{"-" * 60}')
        lines.append('"""')
        lines.append("")
        lines.append("import json")
        lines.append("import subprocess")
        lines.append("import sys")
        lines.append("import os")
        lines.append("from typing import Any, Optional")
        lines.append("")

        # TODO: determine actual path
        lines.append("")
        lines.append(f"# TODO: Set this to the actual path of the compiled bridge binary")
        lines.append(f'BRIDGE_PATH = os.path.join(os.path.dirname(__file__), "bridge{self._bridge_extension(dst_lang)}")')
        lines.append(f"# For compiled bridges, point to the binary:")
        lines.append(f'# BRIDGE_PATH = "./bridge"')
        lines.append("")

        # BridgeClient class
        lines.append("")
        lines.append("class BridgeClient:")
        lines.append('    """Client for the subprocess-based cross-language bridge."""')
        lines.append("")
        lines.append("    def __init__(self, bridge_path: str = BRIDGE_PATH, timeout: int = 30):")
        lines.append("        self.bridge_path = bridge_path")
        lines.append("        self.timeout = timeout")
        lines.append("        self._process: Optional[subprocess.Popen] = None")
        lines.append("")
        lines.append("    def start(self):")
        lines.append('        """Start the bridge subprocess."""')
        lines.append("        # TODO: verify the bridge binary exists and is executable")
        lines.append("        # TODO: add environment variable passthrough if needed")
        lines.append("        self._process = subprocess.Popen(")
        lines.append("            [self.bridge_path],")
        lines.append("            stdin=subprocess.PIPE,")
        lines.append("            stdout=subprocess.PIPE,")
        lines.append("            stderr=subprocess.PIPE,")
        lines.append("            text=True,")
        lines.append("        )")
        lines.append("")
        lines.append("    def stop(self):")
        lines.append('        """Stop the bridge subprocess gracefully."""')
        lines.append("        # TODO: add SIGTERM handling, timeout on shutdown")
        lines.append("        if self._process:")
        lines.append("            self._process.terminate()")
        lines.append("            self._process = None")
        lines.append("")
        lines.append("    def _send_command(self, method: str, params: list) -> Any:")
        lines.append('        """Send a JSON-RPC-style command and return the result."""')
        lines.append("        if not self._process:")
        lines.append('            raise RuntimeError("Bridge not started. Call start() first.")')
        lines.append("")
        lines.append("        request = json.dumps({")
        lines.append('            "method": method,')
        lines.append('            "params": params,')
        lines.append("        })")
        lines.append("")
        lines.append("        # TODO: handle NaN/Infinity in serialization (custom JSON encoder)")
        lines.append("        # TODO: add request logging")
        lines.append("        try:")
        lines.append("            self._process.stdin.write(request + \"\\n\")")
        lines.append("            self._process.stdin.flush()")
        lines.append("")
        lines.append("            response = self._process.stdout.readline()")
        lines.append("            if not response:")
        lines.append("                stderr_output = self._process.stderr.read()")
        lines.append(f'                raise RuntimeError(f"Bridge process died. Stderr: {{stderr_output}}")')
        lines.append("")
        lines.append("            result = json.loads(response)")
        lines.append("            if not result.get(\"ok\", False):")
        lines.append(f'                raise RuntimeError(result.get("error", "Unknown bridge error"))')
        lines.append("            return result.get(\"result\")")
        lines.append("        except json.JSONDecodeError as e:")
        lines.append(f'            raise RuntimeError(f"Bridge returned invalid JSON: {{e}}")')
        lines.append("        except subprocess.TimeoutExpired:")
        lines.append(f'            raise RuntimeError("Bridge request timed out ({{self.timeout}}s)")')
        lines.append("")
        lines.append("    def __enter__(self):")
        lines.append("        self.start()")
        lines.append("        return self")
        lines.append("")
        lines.append("    def __exit__(self, exc_type, exc_val, exc_tb):")
        lines.append("        self.stop()")
        lines.append("")

        # Generate convenience methods for each mapping
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            src_func = m.src_function
            dst_func = m.dst_function
            params_str = self._py_params(m)

            lines.append(f"    # Mapping: {src_func} -> bridge/{dst_func} (confidence: {m.confidence})")
            lines.append(f"    # TODO: verify parameter types and order")
            lines.append(f"    def {src_func}_via_bridge({params_str}):")
            lines.append(f'        """Call {dst_name}.{dst_func} via the subprocess bridge."""')
            lines.append(f"        # TODO: verify params match what the bridge expects")
            lines.append(f'        return self._send_command("{dst_func}", [')
            for pm in (m.param_mappings or []):
                p = self._ensure_pm(pm)
                if p.dst_name != "#MISSING":
                    lines.append(f"            {p.src_name},")
            lines.append(f"        ])")
            lines.append("")

        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append('    print("Subprocess bridge module for", BRIDGE_PATH)')
        lines.append("    print(\"Usage:\")")
        lines.append('    print(\'  client = BridgeClient()\')')
        lines.append('    print(\'  client.start()\')')
        lines.append('    print(\'  result = client.some_function(...)\')')
        lines.append('    print(\'  client.stop()\')')

        return "\n".join(lines)

    def _generate_foreign_bridge(self, schema, src_name, dst_name, dst_lang) -> str:
        """Generate the foreign-side bridge CLI program."""
        if dst_lang == "javascript":
            return self._generate_js_bridge(schema, src_name, dst_name)
        elif dst_lang == "rust":
            return self._generate_rust_bridge(schema, src_name, dst_name)
        elif dst_lang == "java":
            return self._generate_java_bridge(schema, src_name, dst_name)
        elif dst_lang == "kotlin":
            return self._generate_kotlin_bridge(schema, src_name, dst_name)
        elif dst_lang == "c_cpp":
            return self._generate_c_bridge(schema, src_name, dst_name)
        else:
            return f"// TODO: bridge stub for unknown language '{dst_lang}'"

    def _generate_js_bridge(self, schema, src_name, dst_name) -> str:
        """Generate JavaScript bridge CLI."""
        lines = [
            f"// GENERATED — {schema.pair_id} JS bridge",
            f"// SPI Protocol: JSON stdin -> JSON stdout",
            f"const readline = require('readline');",
            f"const {dst_name} = require('{dst_name}');",
            f"",
            f"const rl = readline.createInterface({{ input: process.stdin, output: process.stdout, terminal: false }});",
            f"",
            f"rl.on('line', (line) => {{",
            f"    try {{",
            f"        const req = JSON.parse(line);",
            f"        const method = req.method;",
            f"        const params = req.params || [];",
            f"        let result;",
            f"",
            f"        // TODO: implement method dispatch for all mapped functions",
            f"        switch (method) {{",
        ]
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f"            case '{m.dst_function}':")
            lines.append(f"                // TODO: map params: {', '.join(pm.src_name for pm in (m.param_mappings or []))}")
            lines.append(f"                result = {dst_name}.{m.dst_function}(...params);")
            lines.append(f"                break;")

        lines += [
            f"            default:",
            f'                throw new Error(`Unknown method: ${{method}}`);',
            f"        }}",
            f"",
            f"        process.stdout.write(JSON.stringify({{ ok: true, result }}) + '\\n');",
            f"    }} catch (e) {{",
            f"        process.stdout.write(JSON.stringify({{ ok: false, error: e.message }}) + '\\n');",
            f"    }}",
            f"}});",
            f"",
            f"// Signal ready",
            f'process.stderr.write("Bridge ready\\n");',
        ]
        return "\n".join(lines)

    def _generate_rust_bridge(self, schema, src_name, dst_name) -> str:
        """Generate Rust bridge CLI."""
        lines = [
            f"// GENERATED — {schema.pair_id} Rust bridge",
            f"// SPI Protocol: JSON stdin -> JSON stdout",
            f"// Requires: serde, serde_json for JSON I/O",
            f"",
            f"use std::io::{{self, BufRead, Write}};",
            f"use serde_json::Value;",
            f"",
            f"// TODO: add {dst_name} = \"{dst_name}\" to Cargo.toml",
            f"// use {dst_name.replace('-', '_')};",
            f"",
            f"fn main() -> io::Result<()> {{",
            f"    let stdin = io::stdin();",
            f"    let stdout = io::stdout();",
            f"",
            f"    for line in stdin.lock().lines() {{",
            f"        let line = line?;",
            f"        if line.trim().is_empty() {{ continue; }}",
            f"",
            f"        let req: Value = match serde_json::from_str(&line) {{",
            f"            Ok(v) => v,",
            f"            Err(e) => {{",
            f"                let resp = serde_json::json!({{ \"ok\": false, \"error\": e.to_string() }});",
            f"                writeln!(&mut stdout.lock(), \"{{}}\", resp)?;",
            f"                continue;",
            f"            }}",
            f"        }};",
            f"",
            f"        let method = req[\"method\"].as_str().unwrap_or(\"\").to_string();",
            f"        let params = req[\"params\"].as_array().cloned().unwrap_or_default();",
            f"",
            f"        let result = match method.as_str() {{",
        ]
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f'            "{m.dst_function}" => {{')
            lines.append(f"                // TODO: call {dst_name}::{m.dst_function} with deserialized params")
            lines.append(f'                // let result = {dst_name.replace("-", "_")}::{m.dst_function}(...);')
            lines.append(f'                // serde_json::to_value(result).unwrap_or_default()')
            lines.append(f'                todo!("implement {m.dst_function} bridge")')
            lines.append(f"            }}")

        lines += [
            f'            _ => serde_json::json!({{"error": format!("Unknown method: {{}}", method)}}),',
            f"        }};",
            f"",
            f"        let resp = serde_json::json!({{ \"ok\": true, \"result\": result }});",
            f"        writeln!(&mut stdout.lock(), \"{{}}\", resp)?;",
            f"    }}",
            f"",
            f"    Ok(())",
            f"}}",
        ]
        return "\n".join(lines)

    def _generate_java_bridge(self, schema, src_name, dst_name) -> str:
        """Generate Java bridge CLI."""
        lines = [
            f"// GENERATED — {schema.pair_id} Java bridge",
            f"// SPI Protocol: JSON stdin -> JSON stdout",
            f"// Compile: javac Bridge.java && java Bridge",
            f"",
            f"import com.google.gson.Gson;",
            f"import com.google.gson.JsonObject;",
            f"import com.google.gson.JsonParser;",
            f"import java.io.*;",
            f"import java.util.Scanner;",
            f"",
            f"// TODO: import {dst_name} library",
            f"",
            f"public class {dst_name.title().replace('-', '')}Bridge {{",
            f"    private static final Gson gson = new Gson();",
            f"",
            f"    public static void main(String[] args) throws Exception {{",
            f"        Scanner scanner = new Scanner(System.in);",
            f"        PrintWriter out = new PrintWriter(System.out, true);",
            f"",
            f"        while (scanner.hasNextLine()) {{",
            f"            String line = scanner.nextLine().trim();",
            f"            if (line.isEmpty()) continue;",
            f"",
            f"            try {{",
            f"                JsonObject req = JsonParser.parseString(line).getAsJsonObject();",
            f"                String method = req.get(\"method\").getAsString();",
            f"                // TODO: parse params and dispatch",
            f"                Object result = dispatch(method, req);",
            f"                JsonObject resp = new JsonObject();",
            f"                resp.addProperty(\"ok\", true);",
            f"                resp.add(\"result\", gson.toJsonTree(result));",
            f"                out.println(gson.toJson(resp));",
            f"            }} catch (Exception e) {{",
            f"                JsonObject err = new JsonObject();",
            f"                err.addProperty(\"ok\", false);",
            f"                err.addProperty(\"error\", e.getMessage());",
            f"                out.println(gson.toJson(err));",
            f"            }}",
            f"        }}",
            f"    }}",
            f"",
            f"    private static Object dispatch(String method, JsonObject req) throws Exception {{",
            f"        // TODO: implement method dispatch",
        ]
        for mapping in schema.mappings:
            m = self._ensure_mapping(mapping)
            lines.append(f'        if (method.equals("{m.dst_function}")) {{')
            lines.append(f"            // TODO: call {dst_name}.{m.dst_function}")
            lines.append(f"            throw new UnsupportedOperationException(\"Scaffold\");")
            lines.append(f"        }}")
        lines += [
            f'        throw new IllegalArgumentException("Unknown method: " + method);',
            f"    }}",
            f"}}",
        ]
        return "\n".join(lines)

    def _generate_kotlin_bridge(self, schema, src_name, dst_name) -> str:
        """Generate Kotlin bridge CLI."""
        lines = [
            f"// GENERATED — {schema.pair_id} Kotlin bridge",
            f"// SPI Protocol: JSON stdin -> JSON stdout",
            f"// Requires: kotlinx-serialization",
            f"",
            f"import kotlinx.serialization.*",
            f"import kotlinx.serialization.json.*",
            f"",
            f"// TODO: import {dst_name}",
            f"",
            f"fun main() = runBlocking {{",
            f"    val json = Json {{ ignoreUnknownKeys = true }}",
            f"    // TODO: implement stdin/stdout bridge loop",
            f"    println(\"Kotlin bridge scaffold for {schema.pair_id}\")",
            f"}}",
        ]
        return "\n".join(lines)

    def _generate_c_bridge(self, schema, src_name, dst_name) -> str:
        """Generate C bridge CLI."""
        lines = [
            f"// GENERATED — {schema.pair_id} C bridge",
            f"// SPI Protocol: JSON stdin -> JSON stdout",
            f"// Requires: cJSON or similar JSON library",
            f"// Compile: gcc -o bridge bridge.c -lcjson",
            f"",
            f"#include <stdio.h>",
            f"#include <stdlib.h>",
            f"#include <string.h>",
            f"// TODO: include cJSON.h or your JSON parser",
            f"",
            f"int main() {{",
            f"    char line[65536];",
            f"    // TODO: implement stdin/stdout bridge loop with cJSON",
            f'    fprintf(stderr, "C bridge scaffold for {schema.pair_id}\\n");',
            f"    return 0;",
            f"}}",
        ]
        return "\n".join(lines)

    def _generate_build_script(self, schema, dst_lang) -> str:
        """Generate build script for the foreign bridge."""
        lines = [
            f"#!/bin/bash",
            f"# Build script for {schema.pair_id} bridge",
            f"# Generated by glue-engineer v3",
            f"",
            f"set -e",
            f"",
            f"echo \"Building {schema.pair_id} bridge...\"",
            f"",
        ]
        if dst_lang == "rust":
            lines += [
                f"cd {schema.pair_id}/generated",
                f"# TODO: create proper Cargo.toml with {schema.dst.name if schema.dst else '?'} dependency",
                f'echo "Run: cargo build --release"',
                f"# cargo build --release",
                f"# cp target/release/bridge ../bridge",
            ]
        elif dst_lang == "javascript":
            lines += [
                f"cd {schema.pair_id}/generated",
                f"# TODO: ensure npm dependencies are installed",
                f"npm install {schema.dst.name if schema.dst else '?'}",
                f'echo "Bridge ready — run with: node bridge.js"',
            ]
        elif dst_lang in ("java", "kotlin"):
            lines += [
                f"cd {schema.pair_id}/generated",
                f"# TODO: compile bridge",
                f"# javac Bridge.java",
                f'echo "Bridge compiled"',
            ]
        elif dst_lang == "c_cpp":
            lines += [
                f"cd {schema.pair_id}/generated",
                f"# TODO: compile C bridge",
                f"# gcc -o bridge bridge.c -lcjson",
                f'echo "Bridge compiled"',
            ]
        else:
            lines += [
                f"# TODO: implement build for {dst_lang}",
                f'echo "Build script not implemented for {dst_lang}"',
            ]
        lines.append("")
        return "\n".join(lines)

    def _generate_readme(self, schema, dst_lang) -> str:
        """Generate README with cross-language bridge instructions."""
        lines = [
            f"# {schema.pair_id} — Cross-Language Bridge",
            f"",
            f"**Strategy:** subprocess_json ({schema.src.language if schema.src else '?'} -> {dst_lang})",
            f"**Generated:** {now_iso()}",
            f"",
            f"## Overview",
            f"",
            f"Bridges **{schema.src.name if schema.src else '?'}** ({schema.src.language if schema.src else '?'}) "
            f"to **{schema.dst.name if schema.dst else '?'}** ({dst_lang}) via subprocess+JSON protocol.",
            f"",
            f"## Files",
            f"",
            f"- `generated/glue.py` — Python host-side BridgeClient class",
            f"- `generated/bridge.{self._bridge_extension(dst_lang).lstrip('.')}` — {dst_lang} bridge CLI",
            f"- `build.sh` — Build script for the {dst_lang} bridge",
            f"- `schema.json` — Machine-readable interface contract",
            f"",
            f"## Usage",
            f"",
            f"1. Build the {dst_lang} bridge (see build.sh)",
            f"2. Update BRIDGE_PATH in glue.py if needed",
            f"3. Run:",
            f"",
            f"```python",
            f"from generated.glue import BridgeClient",
            f"",
            f"with BridgeClient() as client:",
            f"    result = client.some_function(...)",
            f"    print(result)",
            f"```",
            f"",
            f"## Review Checklist",
            f"",
            f"- [ ] Verify the foreign bridge compiles and runs",
            f"- [ ] Check all JSON serialization handles NaN/Infinity/None",
            f"- [ ] Add timeout handling for subprocess calls",
            f"- [ ] Verify error propagation from {dst_lang} -> Python",
            f"- [ ] Test with non-trivial payloads",
            f"- [ ] Review subprocess lifecycle (start/stop/restart)",
            f"",
            f"## Disclaimer",
            f"",
            f"{SCAFFOLD_DISCLAIMER}",
        ]
        return "\n".join(lines)

    def _bridge_extension(self, lang: str) -> str:
        """Get file extension for the foreign bridge."""
        return {
            "javascript": ".js",
            "rust": ".rs",
            "java": ".java",
            "kotlin": ".kt",
            "c_cpp": ".c",
        }.get(lang, ".txt")

    def _py_params(self, mapping) -> str:
        """Generate Python parameter list from a mapping."""
        params = []
        for pm in (mapping.param_mappings or []):
            p = self._ensure_pm(pm)
            if p.dst_name != "#MISSING":
                params.append(p.src_name)

        if not params:
            return "self"
        return "self, " + ", ".join(params)

    def _ensure_mapping(self, m):
        if isinstance(m, dict):
            return type("Obj", (), {
                "src_function": m.get("src_function", ""),
                "dst_function": m.get("dst_function", ""),
                "confidence": m.get("confidence", 0.0),
                "confidence_label": m.get("confidence_label", ""),
                "param_mappings": m.get("param_mappings", []),
                "error_map": m.get("error_map", {}),
            })()
        return m

    def _ensure_pm(self, p):
        if isinstance(p, dict):
            return type("Obj", (), {
                "src_name": p.get("src_name", ""),
                "dst_name": p.get("dst_name", ""),
                "src_default": p.get("src_default", ""),
                "dst_default": p.get("dst_default", ""),
            })()
        return p