#!/usr/bin/env python3
"""init_manifest.py — Initialize docs/ directory structure and blank manifest.json.

Usage:
    python init_manifest.py [--project-dir <path>] [--force]

Creates:
    docs/
        index.md            (blank template)
        project/
            index.md        (blank template)
            architecture.md (blank template)
            glossary.md     (blank template)
        modules/
            modules.md      (blank index)
        schema/
            manifest.json   (empty manifest with version info)

If --force is set, overwrites existing files.
If --project-dir is specified, scans for source files to seed candidate modules.
"""

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone


MANIFEST_SCHEMA = {
    "version": "1.0.0",
    "generated_at": "",
    "modules": {},
}


DIR_SKELETON = {
    "docs": {
        "index.md": "# docs\n\n<!-- Root index. Auto-generated by doc-weaver. -->\n\n- [[project/index]] — Project overview\n- [[project/architecture]] — Architecture\n- [[project/glossary]] — Glossary\n",
        "project": {
            "index.md": "# Project\n\n<!-- Project overview. Auto-generated by doc-weaver. -->\n\n## Modules\n\n<!-- List modules here -->\n",
            "architecture.md": "# Architecture\n\n<!-- Architecture overview. Auto-generated by doc-weaver. -->\n\n## Module Dependencies\n\n<!-- Describe dependencies here -->\n",
            "glossary.md": "# Glossary\n\n<!-- Glossary of terms. Auto-generated by doc-weaver. -->\n",
        },
        "modules": {
            "modules.md": "# Modules\n\n<!-- Module index. Auto-generated by doc-weaver. -->\n",
        },
        "schema": {
            # manifest.json is written separately
        },
    },
}


def create_skeleton(base_dir: str, skeleton: dict, force: bool = False, prefix: str = "") -> None:
    """Recursively create directory skeleton from dict."""
    for name, content in skeleton.items():
        path = os.path.join(base_dir, name)
        if isinstance(content, dict):
            os.makedirs(path, exist_ok=True)
            create_skeleton(path, content, force, prefix=f"{prefix}/{name}")
        else:
            if os.path.exists(path) and not force:
                print(f"  [skip] {path} (exists, use --force to overwrite)")
                continue
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  [create] {path}")


def scan_source_files(project_dir: str) -> list[dict]:
    """Scan common source file patterns to seed candidate modules."""
    source_extensions = {
        ".py": "python",
        ".js": "javascript",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".php": "php",
        ".rs": "rust",
        ".go": "go",
        ".java": "java",
        ".kt": "kotlin",
        ".c": "c",
        ".cpp": "cpp",
        ".h": "c",
        ".hpp": "cpp",
        ".rb": "ruby",
        ".swift": "swift",
    }

    candidates = []
    for root, dirs, files in os.walk(project_dir):
        # Skip common non-source directories
        dirs[:] = [d for d in dirs if not d.startswith((".", "node_modules", "venv", "__pycache__",
                                                         "target", "build", "dist", "vendor", ".git"))]
        for file in files:
            ext = os.path.splitext(file)[1]
            if ext in source_extensions:
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, project_dir)
                lang = source_extensions[ext]
                # Try to infer module name from directory structure
                parts = rel_path.replace("\\", "/").split("/")
                if len(parts) >= 2 and parts[0] == "src":
                    module_name = parts[1]
                elif len(parts) >= 2:
                    module_name = parts[0]
                else:
                    module_name = os.path.splitext(parts[0])[0]

                candidates.append({
                    "path": rel_path,
                    "language": lang,
                    "suggested_module": module_name,
                })

    return candidates


def build_manifest(project_dir: str | None, force: bool) -> dict:
    """Build the initial manifest.json content."""
    manifest = dict(MANIFEST_SCHEMA)
    manifest["generated_at"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if project_dir:
        candidates = scan_source_files(project_dir)
        # Group by suggested module name
        modules: dict[str, dict] = {}
        for c in candidates:
            name = c["suggested_module"]
            if name not in modules:
                modules[name] = {
                    "source_paths": [],
                    "hash": "",
                    "mtime": "",
                    "doc_status": "needs_create",
                    "doc_path": f"docs/modules/{name}.md",
                    "schema_path": f"docs/schema/{name}.schema.json",
                    "exports": [],
                    "dependencies": [],
                    "consumers": [],
                    "languages": [],
                }
            if c["path"] not in modules[name]["source_paths"]:
                modules[name]["source_paths"].append(c["path"].replace("\\", "/"))
            if c["language"] not in modules[name]["languages"]:
                modules[name]["languages"].append(c["language"])

        # Compute initial hash + mtime for each module
        for mod_name, mod_data in modules.items():
            hash_inputs = []
            mtimes = []
            for sp in mod_data["source_paths"]:
                full_path = os.path.join(project_dir, sp)
                if os.path.isfile(full_path):
                    try:
                        stat = os.stat(full_path)
                        size = stat.st_size
                        mtime = stat.st_mtime
                        mtimes.append(mtime)
                        sha = hashlib.sha256()
                        with open(full_path, "rb") as f:
                            sha.update(f.read(4096))
                            sha.update(str(size).encode())
                            sha.update(str(mtime).encode())
                        hash_inputs.append(sha.hexdigest())
                    except OSError:
                        pass
            if hash_inputs:
                combined = hashlib.sha256()
                for h in hash_inputs:
                    combined.update(h.encode())
                mod_data["hash"] = combined.hexdigest()
            if mtimes:
                mod_data["mtime"] = datetime.fromtimestamp(max(mtimes), tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        manifest["modules"] = modules
        print(f"  [scan] Found {len(candidates)} source files across {len(modules)} candidate modules")

    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize docs/ directory and manifest.json")
    parser.add_argument("--project-dir", "-p", default=None,
                        help="Project directory to scan for source files")
    parser.add_argument("--force", "-f", action="store_true",
                        help="Overwrite existing files")
    parser.add_argument("--base-dir", "-b", default=".",
                        help="Base directory to create docs/ in (default: current dir)")
    args = parser.parse_args()

    base = os.path.abspath(args.base_dir)
    docs_dir = os.path.join(base, "docs")

    print(f"[init] Setting up docs/ in {base}")

    # Create skeleton
    os.makedirs(docs_dir, exist_ok=True)
    create_skeleton(base, DIR_SKELETON, args.force)

    # Write manifest
    manifest_path = os.path.join(docs_dir, "schema", "manifest.json")
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)

    if os.path.exists(manifest_path) and not args.force:
        print(f"  [skip] {manifest_path} (exists, use --force to overwrite)")
    else:
        project_dir = os.path.abspath(args.project_dir) if args.project_dir else None
        manifest = build_manifest(project_dir, args.force)
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
        print(f"  [create] {manifest_path}")

    print(f"[init] Done. docs/ skeleton is ready at {docs_dir}")


if __name__ == "__main__":
    main()